services:
  # Main database
  db:
    image: postgres:16
    restart: always
    ports:
      - "9081:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/home/postgres/pgdata/data

  # Authentication management and portal
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    restart: always
    ports:
      - "9082:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev # --import-realm
    volumes:
      - keycloak_data:/opt/keycloak/data
    # configs:
    #   - source: keycloak-realm
    #     target: /opt/keycloak/data/import/impolar.json

volumes:
  pg_data:
  keycloak_data:
# configs:
#   keycloak-realm:
#     content: |
