// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationPlatform.Data;
using NotificationPlatform.Models.Email;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationPlatform.Migrations
{
    [DbContext(typeof(NotificationPlatformContext))]
    [Migration("20250202113334_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "email_contact_property_type", new[] { "choice", "date", "number", "string" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("EmailConfigurations");
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EmailConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmailContactPropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailConfigurationId");

                    b.HasIndex("EmailContactPropertyId");

                    b.ToTable("EmailContacts");
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContactProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmailConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<EmailContactPropertyType>("Type")
                        .HasColumnType("email_contact_property_type");

                    b.HasKey("Id");

                    b.HasIndex("EmailConfigurationId");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.ToTable("EmailContactProperties");

                    b.HasDiscriminator<EmailContactPropertyType>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NotificationPlatform.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContactChoiceProperty", b =>
                {
                    b.HasBaseType("NotificationPlatform.Models.Email.EmailContactProperty");

                    b.PrimitiveCollection<string[]>("Choices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue(EmailContactPropertyType.Choice);
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContactDateProperty", b =>
                {
                    b.HasBaseType("NotificationPlatform.Models.Email.EmailContactProperty");

                    b.HasDiscriminator().HasValue(EmailContactPropertyType.Date);
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContactNumberProperty", b =>
                {
                    b.HasBaseType("NotificationPlatform.Models.Email.EmailContactProperty");

                    b.HasDiscriminator().HasValue(EmailContactPropertyType.Number);
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContactStringProperty", b =>
                {
                    b.HasBaseType("NotificationPlatform.Models.Email.EmailContactProperty");

                    b.HasDiscriminator().HasValue(EmailContactPropertyType.String);
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailConfiguration", b =>
                {
                    b.HasOne("NotificationPlatform.Models.Project", "Project")
                        .WithOne("EmailConfiguration")
                        .HasForeignKey("NotificationPlatform.Models.Email.EmailConfiguration", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContact", b =>
                {
                    b.HasOne("NotificationPlatform.Models.Email.EmailConfiguration", null)
                        .WithMany("EmailContacts")
                        .HasForeignKey("EmailConfigurationId");

                    b.HasOne("NotificationPlatform.Models.Email.EmailContactProperty", null)
                        .WithMany("EmailContacts")
                        .HasForeignKey("EmailContactPropertyId");
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContactProperty", b =>
                {
                    b.HasOne("NotificationPlatform.Models.Email.EmailConfiguration", "EmailConfiguration")
                        .WithMany("EmailContactProperties")
                        .HasForeignKey("EmailConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailConfiguration");
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailConfiguration", b =>
                {
                    b.Navigation("EmailContactProperties");

                    b.Navigation("EmailContacts");
                });

            modelBuilder.Entity("NotificationPlatform.Models.Email.EmailContactProperty", b =>
                {
                    b.Navigation("EmailContacts");
                });

            modelBuilder.Entity("NotificationPlatform.Models.Project", b =>
                {
                    b.Navigation("EmailConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
