services:
  # Main database
  db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    ports:
      - "9081:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/home/postgres/pgdata/dat

  authentik-server:
    image: ghcr.io/goauthentik/server:2025.10
    command: server
    depends_on:
      db:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: db
      AUTHENTIK_POSTGRESQL__NAME: notification_platform
      AUTHENTIK_POSTGRESQL__USER: admin
      AUTHENTIK_POSTGRESQL__PASSWORD: admin
      AUTHENTIK_SECRET_KEY: secretkey
      AUTHENTIK_BOOTSTRAP_PASSWORD: admin
      AUTHENTIK_BOOTSTRAP_EMAIL: admin@admin.com
    ports:
      - 9054:9000
      # - ${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped

  authentik-worker:
    image: ghcr.io/goauthentik/server:2025.10
    command: worker
    depends_on:
      db:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: db
      AUTHENTIK_POSTGRESQL__NAME: notification_platform
      AUTHENTIK_POSTGRESQL__USER: admin
      AUTHENTIK_POSTGRESQL__PASSWORD: admin
      AUTHENTIK_SECRET_KEY: secretkey
      AUTHENTIK_BOOTSTRAP_PASSWORD: admin
      AUTHENTIK_BOOTSTRAP_EMAIL: admin@admin.com
    restart: unless-stopped
    user: root
    volumes:
      - ./Authentik/Blueprints:/blueprints/impolar

volumes:
  pg_data:
